### ISSUE TITLE
How do we include domain name in our LOD?

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#123]
Sometimes, we may want to explicitly include domain name in a dataset, as distinct from website/homepage. This may be true for the dotcoop dataset. 

Which ontology/vocab/predicate should we use?

**Comment by joebillings** [comment]
I think we should be considering the domains owned by coops as assets. We could either add this to our version of ESSGlobal or use the Organization vocab in its hierarchy.

**Comment by sunnydean** [comment]
We should drop an email to Joe

**Comment by wu-lee** [comment]
Searching the web finds this, which I've not yet read in detail:
- https://www.researchgate.net/publication/4174836_Developing_an_Ontology_for_the_Domain_Name_System

**Comment by wu-lee** [comment]
More:
- https://stackoverflow.com/questions/16366904/rdf-vocabulary-for-describing-uri-components

Which links to:
- https://www.w3.org/wiki/URI
- http://uri4uri.net/ (a ha-ha-only-serious April Fools joke)
- http://code.google.com/p/court/wiki/COIN (defunct, see [archive.org](https://web.archive.org/web/20170101023727/https://code.google.com/archive/p/court/wikis/COIN.wiki))

**Comment by wu-lee** [comment]
The DNS ontology schema was published here, but that domain no longer exists, and isn't cached on the Wayback archive:

http://www.dhpc.adelaide.edu.au/ontologies/dns.html

However, I found a search engine for ontologies:

http://lov.okfn.org/dataset/lov/

Which finds the uri4uri and another, proton. Possibly we could use one of these terms:

http://uri4uri.net/domain *(nice insider joke on the [404s][3] on this site)*

[3]: http://uri4uri.net/Domain

Or:

http://www.ontotext.com/proton/protonext.html#InternetDomain

Alternatively we could email the authors [1] and [2] for the schema information.

[1]: mailto:nickolas.falkner@adelaide.edu.au
[2]: mailto:andrew@cs.adelaide.edu.au

However, since "Internet Domain" seems to exist in several ontologies on LOV (see above) I also wonder if the right thing is to invent our own vocab and allow other people to map that to their own as necessary.
