### ISSUE TITLE
The css files are being positioned incorrectly under www

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#171]
When the css files are positioned under www for deployment of html version of linked data files, they are positioned into a level deeper then designed, i.e into ../www/css/css rather then ../www/css

**Comment by sunnydean** [comment]
e.g. https://data1.solidarityeconomy.coop/dotcooptestNewData/index.html

**Comment by wu-lee** [comment]
This is I think now fixed, as per SolidarityEconomyAssociation/open-data@3072f2c4b. I've tested with a deploy of the dot-coop data using the open-data repository to https://dev.data.solidarityeconomy.coop/dotcooptestNewData/index.html

**Comment by wu-lee** [comment]
Reassigning to @ColmMassey for review

**Comment by ColmMassey** [comment]
The index page can see the css, but if you select individual co-op data, that page can't.
https://data1.solidarityeconomy.coop/dotcooptestNewData/18207220.html

**Comment by wu-lee** [comment]
I noticed that - however, it's because the data page generated (with the fixed CSS) links to a w3id URL, i.e. this:

   https://w3id.solidarityeconomy.coop/dotcooptestNewData/18207220

...which then redirects back to the original (broken CSS) data page, i.e. the link you pasted.  The corresponding page in the fixed-CSS data is here:

   https://dev.data.solidarityeconomy.coop/dotcooptestNewData/18207220.html

I could try and regenerate the data to be self-contained: i.e. to have  https://dev.data.solidarityeconomy.coop data pages to link to (say) w3id URLs on https://dev.w3id.solidarityeconomy.coop, and install a w3id redirector site there which redirects back to https://dev.data.solidarityeconomy.coop, but that's more work and depends on  sorting out the w3id installation (see SolidarityEconomyAssociation/technology-and-infrastructure#41).

However, perhaps it's better to regenerate the data on the live sites using the fixed code? This then won't have that issue.  Might need to be done carefully, however.

**Comment by ColmMassey** [comment]
Struggling to follow that. Not essential for this sprint. Happy to leave until next month, if it's tricky.

**Comment by ColmMassey** [comment]
I sense this has now been addressed with correct design of URIs, @wu-lee? Close?

**Comment by wu-lee** [comment]
Yes, the CSS is fixed, so this can be closed.

With correct lod.coop redirection of the registrant URI, they also no longer link to static html from old deployments with broken CSS. And these old deployments should have their CSS fixed when they are re-deployed.
