### ISSUE TITLE
Convert SUSY data to LOD

### ISSUE THREAD

**Issue by matt-wallis** [p6data-coop/ise-linked-open-data#54]
The SUSY data is available at https://data.transformap.co/place/SSEDAS_PARTNER

- [ ] Convert this data to our [Standard CSV](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/lib/se_open_data/csv/standard.rb).
- [ ] Consider how that standard CSV should be evolved to make best use of the SUSY data.
- [ ] Update the library methods used by the [CSV to RDF converter](https://github.com/SolidarityEconomyAssociation/open-data-and-maps/blob/master/data/tools/se_open_data/bin/csv/standard/csv-to-rdf.rb) to generate new RDF triples from any new columns added to the standard CSV as a result of considering the SUSY data.

The SUSY data is licensed as Public Domain, to be compatible with OpenStreetMap. 
It was created by Transformap, and any question about it should be posted to https://discourse.transformap.co/

**Comment by almereyda** [comment]
You will find out that the dataset does not follow a relational database schema, since some entries may involve different keys than others.

I am also wondering why the JSON documents need to be flattened/normalised into a strict CSV schema, before being transformed into an RDF graph again.

Please note the internal data format is prepared to be rendered into JSON-LD by explicitly making use of `id` and `context` properties which could be easily transformed into `@id` and `@context` properties in a later development iteration of https://github.com/TransforMap/data.transformap.co/. In that sense, following the marketing language of *HD ready* 720p displays, we can consider the data origin as *LD ready*. 

For us it would be interesting to know which mappings from the used keys to RDF vocabularies will be established.

**Comment by matt-wallis** [comment]
We use the "standard CSV" because it is a format that is widely understood, and is sufficient for providing _basic_ information about an SSE initiative. It will probably be the simplest way to convert a _basic subset_ of the properties of each SSE initiative into RDF.

However, further investigation should be done for this JSON data, given that it is already _LD ready_  :-) If there's a straightforward way to skip the intermediate step (CSV) then that would probably be better. 

The JSON data has an `_id` property. e.g. `"_id":"4a429c6bcd8f88167b04c98bbe119f89"`. Is this suitable for generating a _persistent_ URI for the object? i.e. Is this datum persistent in each object in the OpenStreetMap database?   

> Please note the internal data format is prepared to be rendered into JSON-LD by explicitly making use of id and context properties

I can't see a `context` property in the JSON.

**Comment by almereyda** [comment]
I agree it would be interesting to explore how to avoid an intermediary step, especially since we are targeting LOD since the very first beginning, but also had to fight against design patterns imported from OpenStreetMap that work against it.

Please note the OpenStreetMap database is not involved at all here. Yet each `id` is a UUID to be considered a permanent identifier. The `versions` endpoint already provides a `_uri` property which allows direct addressing of individual changes.

- https://data.transformap.co/place/4a429c6bcd8f88167b04c98bbe119f89/versions

The `context` is currently only used in the database and not yet exposed to the wider public. You find preliminary layouts within the fixtures of the data service. They are not up to date to the actual implementation, nor complete.

Please infer from

- https://github.com/TransforMap/data.transformap.co/blob/master/test/fixtures/poi-read-from-api.json
- https://github.com/TransforMap/data.transformap.co/commit/79b5d74ad336647c954f82362b117dddf38c670a
- https://github.com/TransforMap/data.transformap.co/blob/master/test/fixtures/database/journal.json
- https://github.com/TransforMap/data.transformap.co/blob/master/test/fixtures/database/version.json

what we were trying to do. If you have a local CouchDB instance, I can offer you to replicate the raw data set for further inspection. It may also very well be that we misunderstood the scopes of `type` and `context`.

**Comment by matt-wallis** [comment]
@almereyda - thanks for the information. Just to let you know that it will be quite a while before we get to do work on this, but it's great to have the information you provided as a place to start that work.

**Comment by almereyda** [comment]
Please note that the dataset is permanently available under

- https://susy-mapviewer.github.io/transformap-viewer/susydata-fallback.json
